---
- name: apply common configuration to all nodes
  hosts: all
  become: true 
  roles:
    - common
    - wtcross.sudoers
  vars_files:
    - roles/common/vars/secret.yml

- name: apply backup server configuration
  hosts: backup
  become: true
  roles:
    - docker
    - backuppc4

- name: apply docker configuration
  hosts: docker
  become: true
  roles:
    - docker

- name: apply lan configuration
  hosts: lan
  become: true
  roles:
    - avahi  

- name: apply dhcp configuration
  hosts: raspberrypi.local
  become: true
  roles:
    - dhcp

- name: apply humidity/temperature sensor configuration
  hosts: raspberrypi.local
  become: true
  roles:
    - hum_temp_sensor

- name: apply email configuration
  hosts: postesel.bachert.it
  become: true
  roles:
    - email

- name: apply undervolt configuration
  hosts: eselgurke.local
  become: true
  roles:
    - undervolt

- name: apply desktop-cleanup
  hosts: eselgurke.local
  become: true
  roles:
    - desktop-cleanup

- name: apply PulseAudio configuration
  hosts: eselgurke.local
  become: true
  roles:
    - pulseaudio

- name: apply log2ram
  hosts: raspberrypi.local
  become: true
  roles:
    - log2ram

- name: apply tftp
  hosts: raspberrypi.local
  become: true
  roles:
    - tftp

#- name: apply pisurveillance
#  hosts: raspberrypi.local
#  become: true
#  roles:
#    - pisurveillance
#