- name: desktop - add Signal signing key
  ansible.builtin.apt_key:
    id: DBA36B5181D0C816F630E889D980A17457F6FB06
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: present

    # 16762A2603D5B6EEA51B0CB378BAECFF0E46390F

- name: desktop - add Signal repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=DBA36B5181D0C816F630E889D980A17457F6FB06] https://updates.signal.org/desktop/apt xenial main
    state: present

- name: desktop - add LibreOffice repository
  ansible.builtin.apt_repository:
    repo: ppa:libreoffice/ppa
    state: present

- name: desktop - install packages
  apt:
    state: present
    name:
      - pulseaudio
      - x11-xserver-utils
      - light
      - network-manager
      - autorandr
      - firefox
      - thunderbird
      - keepassxc
      - go-mtpfs
      - signal-desktop
      - gimp
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager
      - qemu-system-x86
      - libvirt-bin
      - wireguard-tools
      - wireshark
      - vlc
      - smbclient
      - cifs-utils
      - cups
      - system-config-printer
      - libreoffice
      - gnome-keyring
      - docker.io
      - wine32
      - wine64
      - udiskie # auto-mount for i3wm
      - sysstat
      - playonlinux
      - chromium-browser
      - steam
      - texlive
      - texlive-science
      - lmodern
      - rdiff-backup
      - vim
      - build-essential
      - openssh-server
      - vscodium      

- name: desktop - enable quiet boot
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: GRUB_CMDLINE_LINUX_DEFAULT="quiet"
  notify: Update GRUB

- name: desktop - disable Ubuntu cloud init
  ansible.builtin.file:
    path: /etc/cloud/cloud-init.disabled
    state: touch
    owner: root
    group: root
    mode: u=r,g=r,o=r

#Disable Dell keyboard illumination
    #https://askubuntu.com/questions/700069/keyboard-backlight-turns-on-after-lock-screen-display-on
    #/etc/dbus-1/system.d/org.freedesktop.UPower.conf
    #    <deny  send_destination="org.freedesktop.UPower"
    #           send_interface="org.freedesktop.UPower.KbdBacklight"/>

#Deactivate bluetooth
    #rfkill block bluetooth

#PlayOnLinux directory
    #ln -s <directory> ~/.PlayOnLinux

#VirtualBox default VM location
    #vboxmanage setproperty machinefolder <directory>
