---
# Example for ADMIN_USERS definition. Real values are included from secret.yml
#ADMIN_USERS:
#  - { name: <username>, password: <password_hash>", keyfile: <path_to_keyfile>" }

SSH_KEY_BACKUPPC: "{{ playbook_dir }}/files/backuppc-id_rsa.pub"

sudoer_rewrite_sudoers_file: False
sudoer_remove_unauthorized_specs: False

sudoer_specs:
  - name: SPEC_SUDO_ADMINS
    comment: Default admin privileges
    users: '%sudo_admin'
    hosts: 'ALL'
    operators: 'ALL'
    commands: 'ALL'
  - name: SPEC_SUDO_BACKUPPC
    comment: Privilege for backup user
    users: 'backuppc'
    hosts: 'ALL'
    tags: 'NOPASSWD'
    commands: '/usr/bin/rsync --server --sender *'
