---
- name: Reload service backuppc
  service:
    name: backuppc
    state: reloaded

- name: Generate a self signed certificate
  openssl_certificate:
    path: "/etc/ssl/certs/{{ ansible_hostname }}.crt"
    privatekey_path: "/etc/ssl/private/{{ ansible_hostname }}.pem"
    csr_path: "/etc/ssl/csr/{{ ansible_hostname }}.csr"
    provider: selfsigned
    force: yes
  notify:
    - Reload service nginx

- name: Reload service nginx
  service:
    name: nginx
    state: reloaded
